import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import koneksi.konek;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class keretaapi extends javax.swing.JFrame {

    public keretaapi() {
        initComponents();
        nonaktif();
        datatabel();
        button_update.setEnabled(false);
        button_delete.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_harga = new javax.swing.JTextField();
        text_jumlah = new javax.swing.JTextField();
        combo_jenis = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        text_biaya = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        radio_anak = new javax.swing.JRadioButton();
        radio_lansia = new javax.swing.JRadioButton();
        radio_dewasa = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        text_asuransi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        text_potongan = new javax.swing.JTextField();
        text_ppn = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        check_konsumsi = new javax.swing.JCheckBox();
        check_wifi = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        text_fasilitas = new javax.swing.JTextField();
        text_total = new javax.swing.JTextField();
        text_kembali = new javax.swing.JTextField();
        text_jumlahuang = new javax.swing.JTextField();
        button_bersih = new javax.swing.JButton();
        button_keluar = new javax.swing.JButton();
        button_update = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_kereta = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        text_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nama Kereta");

        text_nama.setEnabled(false);

        jLabel2.setText("Jumlah Tiket");

        jLabel3.setText("Harga Kereta");

        jLabel4.setText("Biaya");

        jLabel5.setText("Jenis Kereta");

        text_harga.setEnabled(false);

        text_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_jumlahActionPerformed(evt);
            }
        });
        text_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_jumlahKeyPressed(evt);
            }
        });

        combo_jenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PILIH", "AG001", "BS001", "JE001" }));
        combo_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_jenisActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel6.setText("Kasir Stasiun");

        text_biaya.setEnabled(false);
        text_biaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_biayaActionPerformed(evt);
            }
        });

        jLabel7.setText("Jenis Penumpang");

        buttonGroup1.add(radio_anak);
        radio_anak.setText("Anak");
        radio_anak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_anakActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_lansia);
        radio_lansia.setText("Lansia");
        radio_lansia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_lansiaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radio_dewasa);
        radio_dewasa.setText("Dewasa");
        radio_dewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_dewasaActionPerformed(evt);
            }
        });

        jLabel8.setText("Biaya Asuransi");

        text_asuransi.setEnabled(false);
        text_asuransi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_asuransiActionPerformed(evt);
            }
        });

        jLabel9.setText("Total Bayar");

        jLabel10.setText("PPN");

        jLabel11.setText("Jumlah Uang");

        jLabel12.setText("Kembali");

        jLabel13.setText("Biaya Potongan");

        text_potongan.setEnabled(false);

        text_ppn.setEnabled(false);

        jLabel14.setText("Fasilitas Tambahan");

        check_konsumsi.setText("Konsumsi");
        check_konsumsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_konsumsiActionPerformed(evt);
            }
        });

        check_wifi.setText("Wifi");
        check_wifi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_wifiActionPerformed(evt);
            }
        });

        jLabel15.setText("Biaya Fasilitas");

        text_fasilitas.setEnabled(false);

        text_total.setEnabled(false);
        text_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_totalActionPerformed(evt);
            }
        });

        text_kembali.setEnabled(false);
        text_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_kembaliActionPerformed(evt);
            }
        });

        text_jumlahuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_jumlahuangActionPerformed(evt);
            }
        });
        text_jumlahuang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                text_jumlahuangKeyPressed(evt);
            }
        });

        button_bersih.setText("Clear");
        button_bersih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_bersihActionPerformed(evt);
            }
        });

        button_keluar.setText("Exit");
        button_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_keluarActionPerformed(evt);
            }
        });

        button_update.setText("Update");
        button_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_updateActionPerformed(evt);
            }
        });

        button_delete.setText("Delete");
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_save.setText("Save");
        button_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_saveActionPerformed(evt);
            }
        });

        tabel_kereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabel_kereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_keretaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel_kereta);

        jLabel16.setText("Id Penyewa");

        text_id.setEditable(false);
        text_id.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(button_bersih))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(radio_dewasa)
                                                .addComponent(text_jumlah)
                                                .addComponent(combo_jenis, 0, 109, Short.MAX_VALUE)
                                                .addComponent(radio_anak)
                                                .addComponent(radio_lansia)
                                                .addComponent(text_jumlahuang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(text_id))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(check_wifi)
                                                .addGap(18, 18, 18)
                                                .addComponent(check_konsumsi)))
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel10)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(text_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9)))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(text_nama)
                                        .addComponent(text_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(text_asuransi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_potongan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_fasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_total, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(button_save)
                                .addGap(46, 46, 46)
                                .addComponent(button_delete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(button_update)
                                .addGap(53, 53, 53)
                                .addComponent(button_keluar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(jLabel6)))
                .addGap(48, 48, 48)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(text_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(combo_jenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radio_anak)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(radio_dewasa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_lansia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(check_wifi)
                                    .addComponent(jLabel14)
                                    .addComponent(check_konsumsi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(text_asuransi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(text_potongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_ppn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_fasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(text_jumlahuang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(text_total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(text_kembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(47, 47, 47)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(button_bersih)
                            .addComponent(button_save)
                            .addComponent(button_delete)
                            .addComponent(button_update)
                            .addComponent(button_keluar))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void text_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_jumlahActionPerformed
    
    private void datatabel(){
    DefaultTableModel tbl = new DefaultTableModel();
        tbl.addColumn("ID Penumpang");
        tbl.addColumn("Nama Kereta");
        tbl.addColumn("Jenis Kereta");
        tbl.addColumn("Jumlah Tiket");
        tbl.addColumn("Harga Tiket");
        tbl.addColumn("Biaya Asuransi");
        tbl.addColumn("Biaya");
        tbl.addColumn("Potongan");
        tbl.addColumn("PPN");
        tbl.addColumn("Total Bayar");
        tbl.addColumn("Jumlah Uang");
        tbl.addColumn("Kembalian");
        tabel_kereta.setModel(tbl);
        
        try{
            Statement input = (Statement) konek.getConnection().createStatement();
            ResultSet res = input.executeQuery("SELECT * FROM kereta_api");
            while(res.next())
            {
                tbl.addRow(new Object[] {
                res.getString("id"),
                res.getString("nama_kereta"),
                res.getString("jenis_kereta"),        
                res.getString("jumlah_tiket"),
                res.getString("harga_tiket"),
                res.getString("biaya_asuransi"),
                res.getString("biaya"),
                res.getString("potongan"),
                res.getString("ppn"),
                res.getString("total_bayar"),
                res.getString("jumlah_uang"),
                res.getString("kembalian")
                }
                );
                tabel_kereta.setModel(tbl);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
}
    
    private void combo_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_jenisActionPerformed
        // TODO add your handling code here:
        if(combo_jenis.getSelectedItem() == "AG001"){
            text_nama.setText("Argo Bromo");
            text_harga.setText("1000000");
        }else if(combo_jenis.getSelectedItem() == "BS001"){
            text_nama.setText("Bima Sakti");
            text_harga.setText("1200000");
        }else if(combo_jenis.getSelectedItem() == "JE001"){
            text_nama.setText("Jakarta Express");
            text_harga.setText("1300000");
        }
        text_jumlah.requestFocus();
    }//GEN-LAST:event_combo_jenisActionPerformed

    private void text_biayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_biayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_biayaActionPerformed

    private void text_jumlahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_jumlahKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() !=10)return;
        int harga = Integer.parseInt(String.valueOf(text_harga.getText()));
        int jumlah = Integer.parseInt(String.valueOf(text_jumlah.getText()));
        int hasil = harga * jumlah;
        text_biaya.setText(String.valueOf(hasil));
        text_fasilitas.setText("0");
        aktif();
        
    }//GEN-LAST:event_text_jumlahKeyPressed
    private void checkbox(){
        if(check_konsumsi.isSelected()== true && check_wifi.isSelected()== false){
            text_fasilitas.setText("10000");
        }else if(check_wifi.isSelected()== true && check_konsumsi.isSelected()== false){
             text_fasilitas.setText("5000");
        }else if(check_wifi.isSelected()== true && check_konsumsi.isSelected()== true){
            text_fasilitas.setText("15000");
        }else{
            text_fasilitas.setText("0");
        }
        try{
        int fasilitas = Integer.parseInt(String.valueOf(text_fasilitas.getText()));
        int potong2 = Integer.parseInt(String.valueOf(text_potongan.getText()));
        int ppn2 = Integer.parseInt(String.valueOf(text_ppn.getText()));
        int total =  potong2 + ppn2 + fasilitas;
        text_total.setText(String.valueOf(total));
        }catch (java.lang.NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }
    private void nonaktif(){
        radio_anak.setEnabled(false);
        radio_dewasa.setEnabled(false);
        radio_lansia.setEnabled(false);
    }
    
    private void aktif(){
        radio_anak.setEnabled(true);
        radio_dewasa.setEnabled(true);
        radio_lansia.setEnabled(true);
    }
    
    private void radiobutton(){
        if(radio_anak.isSelected()){
            radio_dewasa.setSelected(false);
            radio_lansia.setSelected(false);
            
            int potongan = Integer.parseInt(String.valueOf(text_biaya.getText()));
            int persen = (int)((0.15)*potongan);
            text_asuransi.setText(String.valueOf(persen));
        }else if(radio_dewasa.isSelected()){
           radio_anak.setSelected(false);
            radio_lansia.setSelected(false);
            
            int potongan = Integer.parseInt(String.valueOf(text_biaya.getText()));
            int persen = (int)((0.10)*potongan);
            text_asuransi.setText(String.valueOf(persen)); 
        }else if(radio_lansia.isSelected()){
           radio_anak.setSelected(false);
            radio_dewasa.setSelected(false);
            
            int potongan = Integer.parseInt(String.valueOf(text_biaya.getText()));
            int persen = (int)((0.05)*potongan);
            text_asuransi.setText(String.valueOf(persen)); 
        }
        int asuransi = Integer.parseInt(String.valueOf(text_asuransi.getText()));
        int biaya = Integer.parseInt(String.valueOf(text_biaya.getText()));
        int potong = biaya - asuransi;
        text_potongan.setText(String.valueOf(potong));
        
        int pajak = Integer.parseInt(String.valueOf(text_biaya.getText()));
        int ppn = (int) ((0.10)* pajak);
        text_ppn.setText(String.valueOf(ppn));
        
        int fasilitas = Integer.parseInt(String.valueOf(text_fasilitas.getText()));
        int potong2 = Integer.parseInt(String.valueOf(text_potongan.getText()));
        int ppn2 = Integer.parseInt(String.valueOf(text_ppn.getText()));
        int total =  potong2 + ppn2 + fasilitas;
        text_total.setText(String.valueOf(total));
        
    }
    
    private void radio_anakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_anakActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radio_anakActionPerformed

    private void radio_dewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_dewasaActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radio_dewasaActionPerformed

    private void radio_lansiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_lansiaActionPerformed
        // TODO add your handling code here:
        radiobutton();
    }//GEN-LAST:event_radio_lansiaActionPerformed

    private void check_konsumsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_konsumsiActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_check_konsumsiActionPerformed

    private void check_wifiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_wifiActionPerformed
        // TODO add your handling code here:
        checkbox();
    }//GEN-LAST:event_check_wifiActionPerformed

    private void text_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_totalActionPerformed

    private void text_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_kembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_kembaliActionPerformed

    private void text_jumlahuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_jumlahuangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_jumlahuangActionPerformed

    private void text_jumlahuangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_text_jumlahuangKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() !=10)return;
        double jumlahuang = Double.parseDouble(String.valueOf(text_jumlahuang.getText()));
        double totalbayar = Double.parseDouble(String.valueOf(text_total.getText()));
        double kembali = jumlahuang - totalbayar;
        text_kembali.setText(String.valueOf(kembali));
    
    }//GEN-LAST:event_text_jumlahuangKeyPressed

    private void button_bersihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_bersihActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_button_bersihActionPerformed

    private void clear(){
        buttonGroup1.clearSelection();
        check_konsumsi.setSelected(false);
        check_wifi.setSelected(false);
        text_asuransi.setText("");
        text_jumlah.setText("");
        text_jumlahuang.setText("");
        text_kembali.setText("");
        text_ppn.setText("");
        text_nama.setText("");
        text_total.setText("");
        text_biaya.setText("");
        text_fasilitas.setText("");
        text_harga.setText("");
        text_potongan.setText("");
        text_id.setText("");
        combo_jenis.setSelectedIndex(0);
    }
    
    private void button_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_keluarActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do u want to exit?", "Yash",JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_NO_OPTION){
            this.hide();
            new menu().show();
        }
    }//GEN-LAST:event_button_keluarActionPerformed

    private void tabel_keretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_keretaMouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabel_kereta.getModel();
        tabel_kereta.getSelectedRow();
        
        Object id_penumpang = model.getValueAt(tabel_kereta.getSelectedRow(),0);
        text_id.setText(String.valueOf(id_penumpang));
        
        Object nama_kereta = model.getValueAt(tabel_kereta.getSelectedRow(),1 );
        text_nama.setText(String.valueOf(nama_kereta));
        
        Object jenis = model.getValueAt(tabel_kereta.getSelectedRow(),2);
        combo_jenis.setSelectedItem(String.valueOf(jenis));
        
        Object jumlah = model.getValueAt(tabel_kereta.getSelectedRow(),3);
        text_jumlah.setText(String.valueOf(jumlah));
        
        Object harga_tiket = model.getValueAt(tabel_kereta.getSelectedRow(),4);
        text_harga.setText(String.valueOf(harga_tiket));
        
        Object asuransi = model.getValueAt(tabel_kereta.getSelectedRow(),5);
        text_asuransi.setText(String.valueOf(asuransi));
        
        Object biaya = model.getValueAt(tabel_kereta.getSelectedRow(),6);
        text_biaya.setText(String.valueOf(biaya));
        
        Object potongan = model.getValueAt(tabel_kereta.getSelectedRow(),7);
        text_potongan.setText(String.valueOf(potongan));
        
        Object ppn = model.getValueAt(tabel_kereta.getSelectedRow(),8);
        text_ppn.setText(String.valueOf(ppn));
        
        Object total_bayar = model.getValueAt(tabel_kereta.getSelectedRow(),9);
        text_total.setText(String.valueOf(total_bayar));
        
        
        
        
        button_update.setEnabled(true);
        button_delete.setEnabled(true);
        button_save.setEnabled(false);
    }//GEN-LAST:event_tabel_keretaMouseClicked

    private void button_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_saveActionPerformed
        // TODO add your handling code here:
        try{
        String sql = "INSERT INTO kereta_api(nama_kereta,jenis_kereta,jumlah_tiket,harga_tiket,biaya_asuransi,biaya,potongan,ppn,total_bayar,jumlah_uang,kembalian) VALUES ('"+text_nama.getText()+"','"+combo_jenis.getSelectedItem()+"','"+text_jumlah.getText()+"','"+text_harga.getText()+"','"+text_asuransi.getText()+"','"+text_biaya.getText()+"','"+text_potongan.getText()+"','"+text_ppn.getText()+"','"+text_total.getText()+"','"+text_jumlahuang.getText()+"','"+text_kembali.getText()+"')";
        java.sql.Connection conn=(Connection)konek.getConnection();
        java.sql.PreparedStatement pst=conn.prepareStatement(sql);
        pst.execute();
        JOptionPane.showMessageDialog(null, "Penyimpanan Data Berhasil");
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        clear();
        datatabel();
    }//GEN-LAST:event_button_saveActionPerformed

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
        String id_penumpang = text_id.getText();
        String nama_kereta = text_nama.getText();
        String jenis = (String) combo_jenis.getSelectedItem();
        String jumlah = text_jumlah.getText();
        String harga_tiket = text_harga.getText();
        String asuransi = text_asuransi.getText();
        String biaya = text_biaya.getText();
        String potongan = text_potongan.getText();
        String ppn = text_ppn.getText();
        String total_bayar = text_total.getText();
        try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("DELETE FROM kereta_api WHERE id='"+id_penumpang+"' ");
                JOptionPane.showMessageDialog(null, "Succesfull to delete this data");
                statement.close();
                button_save.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Failed to delete this data"+ e.getMessage());
            }
        datatabel();
        clear();
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_updateActionPerformed
        // TODO add your handling code here:
        if(button_update.getText()=="bedit"){
            text_id.requestFocus();
        }else{
            String id_penumpang = text_id.getText();
            String nama_kereta = text_nama.getText();
            String jenis = (String) combo_jenis.getSelectedItem();
            String jumlah = text_jumlah.getText();
            String harga_tiket = text_harga.getText();
            String asuransi = text_asuransi.getText();
            String biaya = text_biaya.getText();
            String potongan = text_potongan.getText();
            String ppn = text_ppn.getText();
            String total_bayar = text_total.getText();
            try{
                Statement statement = (Statement) konek.getConnection().createStatement();
                statement.executeUpdate("UPDATE kereta_api SET nama_kereta='"+nama_kereta+"', jenis_kereta='"+jenis+"', jumlah_tiket='"+jumlah+"', harga_tiket='"+harga_tiket+"', biaya_asuransi='"+asuransi+"', biaya='"+biaya+"', potongan='"+potongan+"', ppn='"+ppn+"', jumlah_uang='"+text_jumlahuang.getText()+"', kembalian='"+text_kembali.getText()+"' ,total_bayar='"+total_bayar+"' " + "WHERE id='"+id_penumpang+"' ");
                JOptionPane.showMessageDialog(null, "Data berhasil di Update");
                clear();
                button_save.setEnabled(true);
            }catch(Exception e){
                JOptionPane.showMessageDialog(null, "Data gagal di Update"+ e.getMessage());
            }
            datatabel();
        }
    }//GEN-LAST:event_button_updateActionPerformed

    private void text_asuransiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_asuransiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_asuransiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keretaapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keretaapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keretaapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keretaapi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keretaapi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton button_bersih;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_keluar;
    private javax.swing.JButton button_save;
    private javax.swing.JButton button_update;
    private javax.swing.JCheckBox check_konsumsi;
    private javax.swing.JCheckBox check_wifi;
    private javax.swing.JComboBox combo_jenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton radio_anak;
    private javax.swing.JRadioButton radio_dewasa;
    private javax.swing.JRadioButton radio_lansia;
    private javax.swing.JTable tabel_kereta;
    private javax.swing.JTextField text_asuransi;
    private javax.swing.JTextField text_biaya;
    private javax.swing.JTextField text_fasilitas;
    private javax.swing.JTextField text_harga;
    private javax.swing.JTextField text_id;
    private javax.swing.JTextField text_jumlah;
    private javax.swing.JTextField text_jumlahuang;
    private javax.swing.JTextField text_kembali;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_potongan;
    private javax.swing.JTextField text_ppn;
    private javax.swing.JTextField text_total;
    // End of variables declaration//GEN-END:variables
}
