/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author RPL
 */
import java.awt.Color;
import java.awt.Font;
public class lat2 extends javax.swing.JFrame {

    /**
     * Creates new form lat3
     */
    public lat2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb_font = new javax.swing.JLabel();
        lb_size = new javax.swing.JLabel();
        lb_warna = new javax.swing.JLabel();
        cb_font = new javax.swing.JComboBox();
        cb_size = new javax.swing.JComboBox();
        cb_warna = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_tampil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lb_font.setText("Font");

        lb_size.setText("Size");

        lb_warna.setText("Warna");

        cb_font.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arial", "Calibri", "Tahoma" }));
        cb_font.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_fontActionPerformed(evt);
            }
        });

        cb_size.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "14", "16", "18" }));
        cb_size.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_sizeActionPerformed(evt);
            }
        });

        cb_warna.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Merah", "Kuning", "Hijau" }));
        cb_warna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_warnaActionPerformed(evt);
            }
        });

        ta_tampil.setColumns(20);
        ta_tampil.setRows(5);
        jScrollPane1.setViewportView(ta_tampil);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lb_font)
                        .addGap(97, 97, 97)
                        .addComponent(cb_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_warna)
                            .addComponent(lb_size))
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cb_size, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_warna, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_font))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cb_size, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_size, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb_warna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_fontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_fontActionPerformed
        // TODO add your handling code here:
        if(cb_font.getSelectedItem() == "Arial") {
            ta_tampil.setFont(new Font ("Arial",Font.PLAIN,12));
        }
        else if (cb_font.getSelectedItem() == "Calibri") {
            ta_tampil.setFont(new Font ("Calibri",Font.BOLD,12));
        }
        else if (cb_font.getSelectedItem() == "Tahoma") {
            ta_tampil.setFont(new Font ("Tahoma",Font.ITALIC,12));
        }
    }//GEN-LAST:event_cb_fontActionPerformed

    private void cb_sizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_sizeActionPerformed
        // TODO add your handling code here:
        if(cb_size.getSelectedItem() == "14") {
            ta_tampil.setFont(new Font(ta_tampil.getFont().getName(), ta_tampil.getFont().getStyle(),14));
        }
        else if(cb_size.getSelectedItem() == "16") {
            ta_tampil.setFont(new Font(ta_tampil.getFont().getName(), ta_tampil.getFont().getStyle(),16));
        }
        else{
            ta_tampil.setFont(new Font(ta_tampil.getFont().getName(), ta_tampil.getFont().getStyle(),18));
        }
    }//GEN-LAST:event_cb_sizeActionPerformed

    private void cb_warnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_warnaActionPerformed
        // TODO add your handling code here:
        if(cb_warna.getSelectedItem() == "Merah") {
            ta_tampil.setForeground(Color.RED);
        }
        else if(cb_warna.getSelectedItem() == "Kuning") {
            ta_tampil.setForeground(Color.YELLOW);
        }
        if(cb_warna.getSelectedItem() == "Hijau") {
            ta_tampil.setForeground(Color.GREEN);
        }
    }//GEN-LAST:event_cb_warnaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lat2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lat2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb_font;
    private javax.swing.JComboBox cb_size;
    private javax.swing.JComboBox cb_warna;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_font;
    private javax.swing.JLabel lb_size;
    private javax.swing.JLabel lb_warna;
    private javax.swing.JTextArea ta_tampil;
    // End of variables declaration//GEN-END:variables
}
